# Generated by Django 3.2.5 on 2022-05-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gioithieuvieclam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='anh_dai_dien',
            field=models.ImageField(default='static/upload/avatarDefault.jpg', null=True, upload_to='static/upload/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='cv',
            field=models.FileField(null=True, upload_to='static/cv/%Y/%m'),
        ),
    ]
